name: Build & Publish NuGet Packages

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Pack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - src/Viam.Client/Viam.Client.csproj
          - src/Viam.Core/Viam.Core.csproj
          - src/Viam.ModularResources/Viam.ModularResources.csproj
          - src/Viam.Serialization/Viam.Serialization.csproj

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0
            9.0

      - name: Determine version
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF##refs/tags/v}"
          else
            VERSION="0.0.${{ github.run_number }}-dev"
          fi

          echo "Using version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build & Pack
        run: dotnet pack -c Release \
          /p:Version=${{ steps.set_version.outputs.version }} \
          /p:PackageVersion=${{ steps.set_version.outputs.version }} \
          -o ./artifacts ${{ matrix.project }}

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages-${{ matrix.project }}
          path: ./artifacts/*.nupkg

      - name: Remove Symbols Packages (for GitHub feed)
        if: startsWith(github.ref, 'refs/tags/v') && github.repository != 'viamrobotics/viam-dotnet-sdk'
        run: rm -f ./artifacts/*symbols.nupkg

      - name: Push to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v') && github.repository != 'viamrobotics/viam-dotnet-sdk'
        run: dotnet nuget push ./artifacts/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key "${{ secrets.GITHUB_TOKEN }}"

      - name: Push to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'viamrobotics/viam-dotnet-sdk'
        run: dotnet nuget push ./artifacts/*.nupkg \
          --source "https://api.nuget.org/v3/index.json" \
          --api-key "${{ secrets.NUGET_API_KEY }}"
