name: Build & Publish NuGet Packages

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Pack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - src/Viam.Client/Viam.Client.csproj
          - src/Viam.Core/Viam.Core.csproj
          - src/Viam.ModularResources/Viam.ModularResources.csproj
          - src/Viam.Serialization/Viam.Serialization.csproj
          - src/Viam.Contracts/Viam.Contracts.csproj

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0
            9.0
      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Determine version
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF##refs/tags/v}"
          else
            VERSION="0.0.${{ github.run_number }}-dev"
          fi

          echo "Using version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Set artifact name from project path
        id: set_artifact
        run: |
            PROJECT_PATH="${{ matrix.project }}"
            VERSION="${{ steps.set_version.outputs.version }}"

            # Extract "Viam.Client" from "src/Viam.Client/Viam.Client.csproj"
            PACKAGE_ID=$(basename "$PROJECT_PATH" .csproj)
            ARTIFACT_BASE="${PACKAGE_ID}.${VERSION}"

            echo "PACKAGE_ID=$PACKAGE_ID"
            echo "ARTIFACT_BASE=$ARTIFACT_BASE"

            echo "name=$PACKAGE_ID" >> "$GITHUB_OUTPUT"
            echo "base=$ARTIFACT_BASE" >> "$GITHUB_OUTPUT"

      - name: Hydrate Proto files
        run: dotnet build src/Viam.Contracts/Viam.Contracts.csproj -t:ExportProtos

      - name: Build
        run: dotnet build -c Debug /p:Version=${{ steps.set_version.outputs.version }} /p:PackageVersion=${{ steps.set_version.outputs.version }} /p:SymbolPackageFormat=snupkg /p:IncludeSymbols=true ${{ matrix.project }}

      - name: Pack
        run: dotnet pack -c Debug /p:Version=${{ steps.set_version.outputs.version }} /p:PackageVersion=${{ steps.set_version.outputs.version }} /p:SymbolPackageFormat=snupkg /p:IncludeSymbols=true -o "${{ github.workspace }}/artifacts" ${{ matrix.project }}

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact.outputs.base }}.nupkg
          path: "${{ github.workspace }}/artifacts/${{ steps.set_artifact.outputs.base }}.nupkg"

      - name: Upload NuGet symbols package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact.outputs.base }}.symbols.nupkg
          path: "${{ github.workspace }}/artifacts/${{ steps.set_artifact.outputs.base }}.snupkg"

      - name: Push to GitHub Packages
        if: github.repository != 'viamrobotics/viam-dotnet-sdk'
        run: dotnet nuget push "${{ github.workspace }}/artifacts/${{ steps.set_artifact.outputs.base }}.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}"

      - name: Push to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'viamrobotics/viam-dotnet-sdk'
        run: dotnet nuget push "${{ github.workspace }}/artifacts/${{ steps.set_artifact.outputs.base }}.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}"
